from enum import Enum, auto

class Tokentype(Enum):
    SEMICOLON = auto()
    QUESTION  = auto()
    COLON = auto()
    COMA = auto()
    NUMBER = auto()
    PRINT = auto()
    INDENT = auto()
    PLUS = auto()
    MINUS = auto()
    MULTIPLY = auto()
    DIVIDE = auto()
    REMAINDER = auto()
    EQUAL = auto()
    BANG = auto()
    OR =  auto()
    AND = auto()
    BIT_AND = auto()
    BIT_OR = auto()
    BIT_XOR = auto()
    LEFT_SWIFT = auto()
    RIGHT_SWIFT = auto()
    BANG_EQUAL = auto()
    EQUAL_EQUAL= auto()
    GREATER= auto()
    LESS = auto()
    GREATER_EQUAL = auto()
    LESS_EQUAL= auto()
    STRING = auto()
    VAR = auto()
    WHILE = auto()
    FOR = auto()
    IF = auto()
    ELSE = auto()
    DO = auto()
    ELIF = auto()
    FUN = auto()
    OPENBRA = auto()
    CLOSEBRA =  auto()
    OPENPARA = auto()
    CLOSEPARA = auto()
    TRUE = auto()
    FALSE = auto()
    EOF = auto()
    MAIN = auto()
    RETURN  = auto()
    INT = auto()
    VOID = auto()
    B_NOT = auto()

class Token:
    def __init__(self, tokentype, lexeme, line):
        self.type = tokentype
        self.lexeme = lexeme
        self.line = line

    def addToken(tokentype, lexeme, line):
        return Token(tokentype, lexeme, line)
